'use client';
import './globals.css'
import React from 'react'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import { getLoggedUser } from '@/api/getLoggedUser';

const gilroy = localFont({
  src: [
    {
      path: '../assets/fonts/Gilroy-Light.otf',
      weight: '400',
    },
    {
      path: '../assets/fonts/Gilroy-ExtraBold.otf',
      weight: '700',
    },
    {
      path: '../assets/fonts/Gilroy-Medium.woff2',
      weight: '500',
    }
  ]
},
)



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) { 

  
React.useEffect(() => {
  const user = getLoggedUser();
  console.log({user});
}, [])


  return (
    <html lang="en">
      <body className={gilroy.className}>{children}</body>
    </html>
  )
}
