import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'

const gilroy = localFont({
  src: [
    {
      path: '../assets/fonts/Gilroy-Light.otf',
      weight: '400',
    },
    {
      path: '../assets/fonts/Gilroy-ExtraBold.otf',
      weight: '700',
    }
  ]
},
)



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={gilroy.className}>{children}</body>
    </html>
  )
}
